version: '{build}'
image: Visual Studio 2015
configuration: Release
platform: x64
clone_folder: 'c:\project'
init:
- cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"'
build_script:
- cmd: |-
    if not exist c:\project\build md c:\project\build
    cd c:\project\build
    cmake -G "Visual Studio 14 2015" -DCMAKE_CXX_FLAGS="-I\"/OpenSSL-Win64/include\"" -DCMAKE_LIBRARY_PATH_FLAG="/OpenSSL-Win64/lib" ..
    cmake --build . --target ALL_BUILD --config Release
