version: '{build}'
image: Visual Studio 2015
configuration: Release
platform: x64

init:
  - cmd: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat"'

build_script:
  - cmd: >-
    mkdir build
    cd build
    cmake "-G%GENERATOR%" -DBUILD_SSL=NO -DOPENSSL_ROOT_DIR=C:\OpenSSL-Win64 ..
    cmake --build . --target ALL_BUILD --config "%CONFIG%"
